CREATE TABLE `creature` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`mapID` SMALLINT(6) NOT NULL DEFAULT '0',
	`entry` INT(11) NOT NULL DEFAULT '0',
	`posX` INT(11) NOT NULL DEFAULT '0',
	`posY` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;

CREATE TABLE `creature_template` (
	`entry` INT(11) NOT NULL AUTO_INCREMENT,
	`skinID` TINYINT(4) NOT NULL DEFAULT '0',
	`name` VARCHAR(50) NULL DEFAULT '',
	`level` TINYINT(4) NOT NULL DEFAULT '0',
	`force` TINYINT(4) NOT NULL DEFAULT '0',
	`stamina` TINYINT(4) NOT NULL DEFAULT '0',
	`dexterity` TINYINT(4) NOT NULL DEFAULT '0',
	`xp` TINYINT(4) NOT NULL DEFAULT '0',
	`state` TINYINT(4) NOT NULL DEFAULT '0',
	`maxRay` MEDIUMINT(9) NOT NULL DEFAULT '5',
	`respawnTime` INT(11) NOT NULL DEFAULT '5000',
	`rank` TINYINT(4) NOT NULL DEFAULT '0',
	`aiType` TINYINT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`entry`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
