#pragma once

enum CMSG : uint8
{
    C_Connexion = 1,
    C_Save = 2,
    C_UnitCreate = 10,
    C_LoadingPong = 11,
    C_StatAction = 12,
    C_UnitGoDirection = 20,
    C_UnitStopMovement = 21,
    C_UnitTalk = 23,
    C_UnitStartAttack = 24,
    C_UnitStopAttack = 25,
    C_UnitEventAction = 26,
    C_UnitAnswerQuestion = 27,
    C_UpdateTitle = 28,
    C_UpdateSkin = 29,
    C_RemoveItem = 30,
    C_ActionItem = 31,
    C_Unequip = 32,
    C_SellItem = 33
};

enum SMSG : uint8
{
    S_Connexion = 1,
    S_PlayerCreate = 10,
    S_KeyBoardBind = 11,
    S_UnitCreate = 12,
    S_UnitRemove = 13,
    S_UnitUpdateResource = 14,
    S_PlayerUpdateXp = 15,
    S_LogDamage = 16,
    S_SwitchMap = 17,
    S_WarningMsg = 18,
    S_CastBar = 19,
    S_UnitGoDirection = 20,
    S_UnitStopMovement = 21,
    S_UnitUpdatePosition = 22,
    S_UnitUpdateOrientation = 23,
    S_UnitTalk = 24,
    S_SrvPlayerMsg = 25,
    S_UnitStartAttack = 26,
    S_UnitStopAttack = 27,
    S_UnitUpdateSkin = 28,
    S_UnitIsInGroup = 29,
    S_UnitPlayVisual = 30,
    S_UnitUpdateStat = 31,
    S_LoadingPing = 32,
    S_ExtraInterface = 33,
    S_UnitMount = 34,
    S_SrvPlayerQuestion = 35,
    S_ExtraInterfaceData = 36,
    S_UnitPlayAuraVisual = 37,
    S_PlayerTitle = 38,
    S_UnitUpdateName = 39,
    S_BlockBind = 40,
    S_PlayerSkin = 41,
    S_PlayerSpell = 42,
    S_PlayerItem = 43,
    S_PlayerEquipment = 44,
    S_PlayerBagSize = 45,
    S_PlayerRemoveItem = 46,
    S_PlayerRemoveEquipment = 47,
    S_PlayerStackItem = 48,
    S_PlayerUpdateCurrency = 49,
    S_SellItemInterface = 50
};